.PHONY: build test clean

build:
	cd database && go build ./...
	cd keygen && go build -o ../bin/keygen .
	cd api && go build -o ../bin/api .

test:
	cd database && go test -v ./...
	cd keygen && go test -v ./...
	cd api && go test -v ./...
	cd tests && go test -v ./...

clean:
	rm -rf bin/
