# Synchronise WSL -> arbre Windows natif pour le build (lanceurs + scripts +
# fork au niveau HEAD), puis verifie des marqueurs de contenu.
# Usage (une ligne chacune) :
#   Copy-Item "\\wsl$\Ubuntu-22.04\home\julien\projet\installer\sync_video_files_to_windows.ps1" -Destination "C:\Users\Administrator\Documents\Projets\projet\installer\" -Force
#   powershell -ExecutionPolicy Bypass -File "C:\Users\Administrator\Documents\Projets\projet\installer\sync_video_files_to_windows.ps1"
$ErrorActionPreference = "Stop"
$Wsl = "\\wsl$\Ubuntu-22.04\home\julien\projet"
$Win = "C:\Users\Administrator\Documents\Projets\projet"
$files = @(
  "docs/FORK_IMPLEMENTATION_STATUS.md",
  "installer/configurator/codec_perf.go",
  "installer/configurator/codec_perf_test.go",
  "installer/configurator/toml_quote.go",
  "installer/configurator/toml_quote_test.go",
  "installer/configurator/main.go",
  "installer/configurator/rustdesk_darwin.go",
  "installer/configurator/rustdesk_linux.go",
  "installer/configurator/rustdesk_windows.go",
  "installer/configurator/config_windows.go",
  "installer/configurator/i18n.go",
  "installer/configurator/service_billing_linux.go",
  "installer/configurator/gui.go",
  "installer/configurator/fleet_uri.go",
  "installer/configurator/api.go",
  "installer/configurator/google_auth.go",
  "installer/configurator/service_billing_gui.go",
  "installer/configurator/config_linux.go",
  "installer/configurator/gui_linux.go",
  "installer/configurator/fleet_gui.go",
  "installer/configurator/folders_test.go",
  "installer/configurator/rustdesk_darwin_test.go",
  "installer/configurator/folders.go",
  "installer/configurator/fleet_uri_test.go",
  "installer/configurator/go.mod",
  "installer/configurator/go.sum",
  "installer/configurator/customer_extras_test.go",
  "installer/configurator/customer_team.go",
  "installer/configurator/customer_gui.go",
  "installer/configurator/customer_api_test.go",
  "installer/configurator/customer_billing.go",
  "installer/configurator/customer_silent_test.go",
  "installer/configurator/customer_gui_test.go",
  "installer/configurator/customer_api.go",
  "installer/configurator/customer_history.go",
  "installer/configurator/customer_gui_panels.go",
  "installer/configurator/customer_services.go",
  "installer/configurator/pin_consistency_test.go",
  "installer/viewer/go.mod",
  "installer/viewer/go.sum",
  "installer/viewer/codec_perf.go",
  "installer/viewer/codec_perf_test.go",
  "installer/viewer/toml_quote.go",
  "installer/viewer/toml_quote_test.go",
  "installer/viewer/fleet_autoupdate.go",
  "installer/viewer/fleet_autoupdate_test.go",
  "installer/viewer/main.go",
  "installer/viewer/main_test.go",
  "installer/viewer/rustdesk_darwin.go",
  "installer/viewer/rustdesk_darwin_test.go",
  "installer/viewer/rustdesk_linux.go",
  "installer/viewer/rustdesk_windows.go",
  "installer/viewer/config_windows.go",
  "installer/build_linux_technicien.ps1",
  "installer/build_technicien_portable.ps1",
  "installer/build_viewer_windows.ps1",
  "scripts/build-rustdesk-windows.ps1",
  "scripts/rustdesk-sciter-vcpkg/vcpkg.json",
  "scripts/mirror-portable-oracle.ps1",
  "scripts/deploy-api-20260927.ps1",
  "rustdesk/.github/workflows/flutter-build.yml",
  "rustdesk/.github/workflows/relaisdesk-mac.yml",
  "rustdesk/Cargo.lock",
  "rustdesk/Cargo.toml",
  "rustdesk/build.py",
  "rustdesk/src/client.rs",
  "rustdesk/src/client/io_loop.rs",
  "rustdesk/src/lib.rs",
  "rustdesk/src/platform/gtk_sudo.rs",
  "rustdesk/src/platform/win_device.rs",
  "rustdesk/src/plugin/manager.rs",
  "rustdesk/src/plugin/native_handlers/macros.rs",
  "rustdesk/src/plugin/native_handlers/session.rs",
  "rustdesk/src/relaisdesk_intervention.rs",
  "rustdesk/src/server/connection.rs",
  "rustdesk/src/server/video_qos.rs",
  "installer/viewer/selfupdate.go",
  "installer/viewer/selfupdate_test.go",
  "installer/viewer/selfupdate_product.go",
  "installer/viewer/selfupdate_spawn_windows.go",
  "installer/viewer/selfupdate_spawn_unix.go",
  "installer/viewer/selfupdate_gui.go",
  "installer/viewer/selfupdate_gui_linux.go",
  "installer/viewer/gui.go",
  "installer/viewer/gui_linux.go",
  "installer/viewer/i18n.go",
  "installer/viewer/api.go",
  "installer/viewer/api_status_test.go",
  "installer/viewer/fleet_linux.go",
  "installer/viewer/fleet_windows.go",
  "installer/viewer/fleet_linux_test.go",
  "installer/configurator/selfupdate.go",
  "installer/configurator/selfupdate_test.go",
  "installer/configurator/selfupdate_product.go",
  "installer/configurator/selfupdate_spawn_windows.go",
  "installer/configurator/selfupdate_spawn_unix.go",
  "installer/configurator/selfupdate_gui.go",
  "installer/configurator/gui.go",
  "installer/configurator/gui_linux.go",
  "installer/configurator/i18n.go",
  "installer/configurator/api_status_test.go",
  "installer/configurator/fleet_tokens.go",
  "installer/configurator/fleet_tokens_test.go",
  "installer/configurator/rustdesk_linux_stage_test.go",
  "installer/viewer/rustdesk_linux_stage_test.go",
  "rustdesk/src/core_main.rs",
  "rustdesk/src/relaisdesk_meter.rs",
  "rustdesk/src/relaisdesk_fleet_linux.rs",
  "rustdesk/libs/pam-safe/src/conv.rs",
  "rustdesk/libs/pam-safe/src/functions.rs",
  "rustdesk/src/server.rs",
  "rustdesk/vendor/glib-0.18.5/RELAISDESK-SECURITY.md",
  "installer/configurator/updates.go",
  "installer/configurator/updates_test.go",
  "installer/configurator/storage.go",
  "installer/configurator/storage_other.go",
  "installer/configurator/credentials_test.go",
  "installer/configurator/rustdesk_windows_test.go",
  "installer/viewer/toml.go",
  "installer/viewer/rustdesk_windows_test.go",
  "installer/nsis/installer.nsi",
  "scripts/deploy-interventions-20260920.ps1"
)
foreach ($f in $files) {
  $src = "$Wsl/$f"
  if (-not (Test-Path -LiteralPath $src)) { throw "Source absente : $src" }
  $dest = Join-Path $Win ($f -replace '/', '\')
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $dest) | Out-Null
  Copy-Item $src -Destination $dest -Force
}
# Marqueurs : @(chemin, motif, estRegex)
$checks = @(
  @("installer\viewer\codec_perf.go", "CodecPreferenceAuto", $false),
  @("installer\configurator\codec_perf.go", "setHwCodecEverywhere", $false),
  @("installer\configurator\fleet_uri.go", "splitCLIArgs", $false),
  @("installer\configurator\customer_api.go", "package main", $false),
  @("scripts\build-rustdesk-windows.ps1", "inline,vram,hwcodec", $false),
  @("scripts\rustdesk-sciter-vcpkg\vcpkg.json", "mfx-dispatch", $false),
  @("rustdesk\src\server\video_qos.rs", "INIT_FPS: u32 = 30", $false),
  @("rustdesk\Cargo.lock", 'name = "ringbuf"\r?\nversion = "0.5.2"', $true),
  @("installer\viewer\config_windows.go", "068898d94547f86a3322835f2580b9516e272ae3040f9b862310f49099665525", $false),
  @("installer\viewer\go.mod", "klauspost/compress", $false),
  @("installer\viewer\fleet_autoupdate.go", "openDataTar", $false),
  @("rustdesk\src\core_main.rs", "--password-file", $false),
  @("installer\viewer\fleet_windows.go", "--password-file", $false),
  @("installer\configurator\updates.go", "RELEASE_KEY_ID", $false),
  @("installer\nsis\installer.nsi", "ENROLLCODE", $false)
)
foreach ($c in $checks) {
  $p = Join-Path $Win $c[0]
  $pattern = $c[1]
  if (-not $c[2]) { $pattern = [regex]::Escape($pattern) }
  if ((Get-Content -LiteralPath $p -Raw) -notmatch $pattern) {
    throw "Marqueur absent dans $($c[0]) : $($c[1])"
  }
}
Write-Host ("SYNC OK : {0} fichiers copies, {1} marqueurs verifies." -f $files.Count, $checks.Count)
